export const GET_EXPLORE_PAGE_DATA_REQ = 'GET_EXPLORE_PAGE_DATA_REQ';
export const GET_EXPLORE_PAGE_DATA_SUCCESS = 'GET_EXPLORE_PAGE_DATA_SUCCESS';
export const GET_EXPLORE_PAGE_DATA_FAIL = 'GET_EXPLORE_PAGE_DATA_FAIL';