export const UPDATE_ALL_POST_REQUEST = 'UPDATE_ALL_POST_REQUEST';
export const UPDATE_ALL_POST_SUCCESS = 'UPDATE_ALL_POST_SUCCESS';
export const UPDATE_ALL_POST_FAIL = 'UPDATE_ALL_POST_FAIL';
export const UPDATE_ALL_POST_RESET = 'UPDATE_ALL_POST_RESET';


export const GET_ALL_POSTS_REQ = 'GET_ALL_POSTS_REQ';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL';

export const USER_POST_REQUEST = 'USER_POST_REQUEST';
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS';
export const USER_POST_FAIL = 'USER_POST_FAIL';